### ISSUE TITLE
Indic-Eng model not found

### ISSUE THREAD

**Issue by suvanbalu** [venmurasu-programming-team/Aug2021-contest#1]
The Indic-Eng v2.0 model couldn't be downloaded. There is an error in the website where the model could be downloaded.

https://storage.googleapis.com/samanantar-public/V0.2/models/indic-en.zip

**Comment by visu** [comment]
Thanks for reporting. Ai4Bharath team is checking. cc @GokulNC

**Comment by suvanbalu** [comment]
It would be nice if your team can rectify the issue at earliest . Or can you suggest us some other models?

**Comment by GokulNC** [comment]
> Or can you suggest us some other models?

You can also try using this meanwhile:
https://github.com/UKPLab/EasyNMT#usage

**Comment by cmrajan** [comment]
#https://github.com/AI4Bharat/indicTrans/issues/19

**Comment by cmrajan** [comment]
AI4Bharat/indicTrans/issues/#19

**Comment by cmrajan** [comment]
AI4Bharat/indicTrans#19

**Comment by GokulNC** [comment]
I hope this would be fixed by today. Apologies for the delay.

**Comment by gowtham1997** [comment]
It's fixed now. 
Please retry downloading the models

**Comment by cmrajan** [comment]
Thanks @gowtham1997 I could download the models.

**Comment by suvanbalu** [comment]
Thanks @gowtham1997
