### ISSUE TITLE
Bleu Score Calculation

### ISSUE THREAD

**Issue by suvanbalu** [venmurasu-programming-team/Aug2021-contest#3]
After translation of the cleaned Tamil files and once we run the blue calculation we get very low points .

And we tried with some random test cases , what we found was an extra quote ("") gives us very less accuracy

So can we ignore all quotes while calculating bleu score ?

@cmrajan @GokulNC

**Comment by GokulNC** [comment]
> once we run the blue calculation we get very low points

It's not necessary to show high BLEU scores for this contest :)
It is just a round to evaluate a few skills. The BLEU scores are highly dependent on the model's quality, over which we do not have control (for this contest).

> So can we ignore all quotes while calculating bleu score ?

It is generally not recommended to do so.
But yes, you can report in your README both accuracies (with and without single/double quotes)

**Comment by Br41ni4c** [comment]
> It's not necessary to show high BLEU scores for this contest :)
 Does that mean that we won't be evaluated based on the BLEU scores that we submit?

**Comment by Br41ni4c** [comment]
>It's not necessary to show high BLEU scores for this contest :)
Does that mean that we won't be evaluated based on the BLEU scores that we submit?

**Comment by Br41ni4c** [comment]
> It's not necessary to show high BLEU scores for this contest :)

Does that mean that we won't be evaluated based on the BLEU scores that we submit?

**Comment by GokulNC** [comment]
Yes, you will not be evaluated based on BLEU scores for this round.
The only thing that matters is your approach and quality of strategy/implementation.
